### ISSUE TITLE
npm package has old index.d.ts

### ISSUE THREAD

**Issue by Whobeu** [kevincastejon/js-raspberrypi-liquid-crystal#14]
The raspberrypi-liquid-crystal package published on npm does not have the latest index.d.ts that is published here. It is missing the three createChar methods:

```
createChar(line: number, chars: Array<number>): Promise<void>;
createCharSync(line: number, chars: Array<number>): void;
createCharASync(line: number, chars: Array<number>, callback: LCDCallback): void;
```
I manually installed it in my node_modules directory but any new installation or npm rebuild reverts to the old version.

**Comment by kevincastejon** [comment]
thanks for warning me about this, the npm version should now be updated
