### ISSUE TITLE
Support for 16x4 LCD

### ISSUE THREAD

**Issue by ghost** [kevincastejon/js-raspberrypi-liquid-crystal#17]
I find your node.js package very helpful. Thank you!

However, there is one hickup I need to fix by hand when I want to use my less common 16x4 display.
Here is a link to its Data Sheet:
https://www.pollin.de/productdownloads/D120628D.PDF

On page 14 the character positions in RAM are listed.

I always apply this diff:
```
<     if(cols == 16 && rows == 4)
<       this._LINEADDRESS = [0x80, 0xC0, 0x90, 0xD0];
<     else
<       this._LINEADDRESS = [0x80, 0xC0, 0x94, 0xD4];
---
>     this._LINEADDRESS = [0x80, 0xC0, 0x94, 0xD4];
```

Perhaps it could be incorporated?

Best wishes,
Sebastian

**Comment by kevincastejon** [comment]
Thanks for bringing my attention on this,
I think it's too much specific adding (specific to this screen cols and rows count), I would prefer to find a way, of inferring these lines addresses  from the rows and cols count, but I don't know if it's even possible.
It makes me wonder if it actually works for 20x4 as I claim on the package doc...
What I could do for now though, is actually make these lines addresses configurable into the constructor as an array of addresses

**Comment by kevincastejon** [comment]
I've created a new branch with this new constructor parameter, unfortunately I have no raspberry nor LCD to test it myself..
Can you please try the branch version and confirm it is working before I merge it and push npm update?

https://github.com/kevincastejon/js-raspberrypi-liquid-crystal/tree/Configurable-lines-addresses

**Comment by ghost** [comment]
Thank you for your efforts. 

I can confirm that the addresses for 20x4 work on these, as I also use them:
https://www.amazon.de/dp/B0822PP3WM

Give me some time, I'll need to figure out what to do. I'll download your branched index.js into my nodered module folder where I usually apply my patch and then adjust where I create my object to include the optional parameter for linesAddresses to specify my displays configuration.

I like the idea of bringing the parameters to the surface.

I'll get back to you,
S

**Comment by ghost** [comment]
Great!

It now works on 16x4 as well as 20x4

This is my constructor for my 16x4:
`const lcd = new LCD(1, 0x27, 16, 4, [0x80, 0xC0, 0x90, 0xD0]);`

Case closed for me,
have a nice weekend,
S

**Comment by kevincastejon** [comment]
thanks for confirming ! I'll merge this on the main branch, and then push the updated package to NPM asap

**Comment by kevincastejon** [comment]
branch merged and updated npm package pushed
