### ISSUE TITLE
Clearing a row rather than whole display

### ISSUE THREAD

**Issue by PPosh98** [kevincastejon/js-raspberrypi-liquid-crystal#2]
Hello.

It's not really an issue but I was wondering whether there is a way to clear a single row rather than the whole display with clearSync()?

Awaiting your response,

Thanks,

Posh.

**Comment by kevincastejon** [comment]
Hi,

clear, clearSync and clearAsync methods actually just offers bindings for the native LCD command "CLEARDISPLAY", that command wipes all the lines.

I could have set up an integer parameter that would have call printLine() under the hood and send CLEARDISPLAY command if no parameter given.
Let me know if such a feature could be useful for you.
(non related but you made me notice that the printLine method was not present on the API doc of the readme, so thx for that ^^)

**Comment by kevincastejon** [comment]
of course for now you can use 'printLine(lineIndex, "");' to clear a specific line.

**Comment by PPosh98** [comment]
Thanks for swift reply.

printLine(lineIndex, "") doesn't seem to work correctly but it's probably just my coding. 

I appreciate the help anyways. Thank you.



> Hi,
> 
> clear, clearSync and clearAsync methods actually just offers bindings for the native LCD command "CLEARDISPLAY", that command wipes all the lines.
> 
> I could have set up an integer parameter that would have call printLine() under the hood and send CLEARDISPLAY command if no parameter given.
> Let me know if such a feature could be useful for you.
> (non related but you made me notice that the printLine method was not present on the API doc of the readme, so thx for that ^^)

I am glad that I could unintentionally help you ( =

**Comment by kevincastejon** [comment]
actually I did not used this package since a long time, I definitely have to update it, I'll try to find some time to dig into your issue

**Comment by PPosh98** [comment]
Appreciate that. This is what i've done to accommodate:

`lcd.printLineSync(2, "                    ");
`

I've got the 20x4 display so I have 20 space characters in between the speech marks. I did this in order to clear all characters on the specified line. Haven't found an alternative yet but it's doing the job.

**Comment by kevincastejon** [comment]
@PPosh98 I cloned and test the repo on my brand new RPI4 with an old 16x2 lcd and actually nothing worked...
Only incoherent characters, can't have a proper 'hello world'...
Can you please provide me info about the version of your RPI and OS ?
(maybe issue come from my lcd)

**Comment by kevincastejon** [comment]
I've decided to continue fitting the Arduino LiquidCrystal API

**Comment by PPosh98** [comment]
I'm sorry I didn't get back to you on your message of 20th March. I was using the new RPi4 too with the standard Raspberry Pi OS.

> I've decided to continue fitting the Arduino LiquidCrystal API

Okay, good luck with that.

**Comment by kevincastejon** [comment]
no problem, free time is gold, the issue I had was the async APIs not working anymore, I "fixed" it temporarily so it should be usable. A proper fix will follow.
