### ISSUE TITLE
Trouble using Promise API

### ISSUE THREAD

**Issue by EmilienLeroy** [kevincastejon/js-raspberrypi-liquid-crystal#7]
Hi,
Before all thanks you for all the work you made. You saved me many hours of development.
I have a trouble with the promise API. I have tried to run the example `printPromiseAwait.js` and it print this on my lcd screen :

![image](https://user-images.githubusercontent.com/31723722/139474135-6ccff87e-a0f8-4268-a4cb-f3a3cb3032e4.png)

But when I use the `printSyncChain.js` example it work perfectly :

![image](https://user-images.githubusercontent.com/31723722/139474189-10148c5d-970f-4b73-81ef-052684ad15c3.png)

I don't no if I missed something during the configuration ! Anyway, actually I can work with the sync API but I don't no if the trouble is from me or is a bug from the library.

## My configuration 
* Raspberry PI 3 B+
* LCD1602
* PCF8574 
* Nodejs 14.17.6
* raspberrypi-liquid-crystal 1.15.0

**Comment by kevincastejon** [comment]
thank you very much for reporting this, unfortunately, I haven't maintained that repo for a while, the last time I tried to use it it was all buggy... And I don't know if it was hardware related or not.
I'm glad you're using it anyway and feel sorry that the promises methods do not work you.
I'll do my best to investigate the issues but I think I won't have the time to do it before 2 months from now..

Ps: maybe you could try with a older nodejs version ? like the 12 or even 10

**Comment by EmilienLeroy** [comment]
Hi @kevincastejon 
Thank you for your answer. I have already implemented your library in my project using the sync api and it works like a charm !
I have tried using node 10 and 12. I get also the same trouble using the promise api. 
But if you don't have time to work on this I will close this issue because the sync api is more than enought !

**Comment by kevincastejon** [comment]
I fixed the async and promise API but it's kinda hacky, I will use the openPromisified i2c-bus method in a future update
